<h1>Websocket Chat Server</h1>
<div id="messages"></div>

<script type="application/javascript">
  console.log("ASDASDASDASD")
var conn = new WebSocket('ws://localhost:8080');

console.log(conn)

conn.addEventListener('open', function(e) {
  addMessage("Connection established!")
  helloWorldPing()
});

conn.addEventListener('message', function(e) {
  addMessage(e.data)
})

function helloWorldPing() {
  if (conn.readyState === conn.OPEN) {
    conn.send('Hello World!');
    setTimeout(helloWorldPing, 3000);
  }
}

function addMessage(message) {
  var messageTag = document.createElement('div');
  messageTag.innerHTML = message;

  // We will display as well as log the message.
  console.log(message)
  document.getElementById('messages')
    .appendChild(messageTag)
}

</script>